source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

abstract_target 'default_pods' do
  pod "AppleGenericKeychain", :path => "../"

  target 'GenericKeychain1'
  target 'GenericKeychain2'
end
