source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

def default_pods
  pod "AppleGenericKeychain", :path => "../"
end

target 'GenericKeychain' do
    default_pods
end

target 'GenericKeychain2' do
    default_pods
end
