source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GenericKeychain', :exclusive => true do
  pod "AppleGenericKeychain", :path => "../"
end

target 'GenericKeychain2', :exclusive => true do
  pod "AppleGenericKeychain", :path => "../"
end
